###
GET {{host}}/user/list
token:{{token}}
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "start_time": "",
  "end_time": "",
  "name": "",
  "phone": "",
  "gender":-1,
  "new": -1,
  "traffic_id": -1,
  "token":"",
  "id":""
}

###
POST {{host}}/user/black/set
token:{{token}}
Content-Type: application/json

{
  "id": 1,
  "black": 0
}

###
GET {{host}}/borrow/list
token:{{token}}
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "name":"Va jacky",
  "postponed": -1,
  "loan_type": -1,
  "status": -1
}

###
GET {{host}}/user/contact
token:{{token}}
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "user_id": 1
}

###
GET {{host}}/user/sms
token:{{token}}
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "user_id": 1
}
###
GET {{host}}/user/app
token:{{token}}
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "user_id": 1
}
###
GET {{host}}/user/call
token:{{token}}
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "user_id": 1
}

###
GET {{host}}/user/detail
token:{{token}}
Content-Type: application/json

{
  "id": 1
}