###
GET {{host}}/user/list
token:{{token}}
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "start_date": "",
  "end_date":"",
  "name": "",
  "mobile":"",
  "sex": "",
  "old":"",
  "traffic_id": "",
  "market_id":"",
  "id": ""
}

###
GET {{host}}/user/contact
token:{{token}}
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "user_id": 1
}

###
GET {{host}}/user/sms
token:{{token}}
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "user_id": 1
}
###
GET {{host}}/user/app
token:{{token}}
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "user_id": 1
}
###
GET {{host}}/user/call
token:{{token}}
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "user_id": 1
}

###
GET {{host}}/user/detail
token:{{token}}
Content-Type: application/json

{
  "page": 1,
  "size": 10,
  "user_id": 1
}